plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'org.spongepowered.mixin' version '0.7.+'
}

version = "${mod_version}"
group = 'com.foxyas.changed_addon'
archivesBaseName = 'ChangedAddon-m1.20.1'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'parchment', version: '2023.09.03-1.20.1'

    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                changed_addon {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                changed_addon {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            args '--mod', 'changed_addon', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')

            mods {
                changed_addon {
                    source sourceSets.main
                }
            }
        }
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    // Mod Location
    flatDir {
        dirs 'libs'
    }

    maven {
        url "https://cursemaven.com"
    }

    maven {
        name = "Changed"
        url = "https://ltxprogrammer.github.io/maven/"
    }

    maven { url "https://maven.shedaniel.me/" }

    //maven {
    //    name = "Changed"
    //    url = "https://raw.githubusercontent.com/foxyas/Changed-Minecraft-Mod/1.20.1-dev/mcmodsrepo/"
    //}

    maven {
        name = "Changed_Local_file"
        url uri("${rootProject.projectDir}/libs")
    }

    maven {
        // location of the maven that hosts JEI files
        name = "Progwml6 maven"
        url = "https://dvs1.progwml6.com/files/maven/"
    }

    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    maven {
        // EMI
        url = "https://maven.terraformersmc.com/"
    }
}

mixin {
    add sourceSets.main, "changed_addon.refmap.json"
    config "changed_addon.mixins.json"
    config "changed_addon.compatibility.mixins.json"
    env {
        remapRefMap = true
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraftVersion}-${forgeVersion}" //Forge Version

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    annotationProcessor project(':ap')

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.4.1")) {
        jarJar.ranged(it, "[0.4.1,)")
    }

    implementation fg.deobf("net.ltxprogrammer.changed:Changed-m1.20.1-f47.4.0:v0.15.7") {
        changing = true
    }//Changed

    implementation fg.deobf("net.zaharenko424.casualties_cubed:casualties_cubed-1.1.0:1.1.0")


    // JEI Mod.
    compileOnly fg.deobf("mezz.jei:jei-${minecraftVersion}-common-api:${jeiVersion}")
    compileOnly fg.deobf("mezz.jei:jei-${minecraftVersion}-forge-api:${jeiVersion}")

    runtimeOnly fg.deobf("mezz.jei:jei-${minecraftVersion}-common:${jeiVersion}")
    runtimeOnly fg.deobf("mezz.jei:jei-${minecraftVersion}-forge:${jeiVersion}")

    // REI Mod.
    compileOnly fg.deobf("me.shedaniel:RoughlyEnoughItems-forge:${reiVersion}")
    compileOnly fg.deobf("me.shedaniel:RoughlyEnoughItems-api-forge:${reiVersion}")
    compileOnly fg.deobf("me.shedaniel.cloth:cloth-config-forge:${clothVersion}")
    compileOnly fg.deobf("dev.architectury:architectury-forge:${archVersion}")

    // EMI
    compileOnly fg.deobf("dev.emi:emi-forge:${emi_version}:api")
    compileOnly fg.deobf("dev.emi:emi-forge:${emi_version}")

    // Gun Mods.
    implementation fg.deobf("com.mrcrayfish.framework:framework-forge-1.20.1-0.8.0:0.8.0")
    implementation fg.deobf("software.bernie.geckolib:geckolib-forge-1.20.1-4.8.3:4.8.3")
    implementation fg.deobf("ttv.migami.jeg:JustEnoughGuns-0.13.2-1.20.1:0.13.2")
    implementation fg.deobf("com.tacz.guns:tacz-1.20.1-1.1.7-hotfix2:1.1.7")

    // First Person Mod.
    implementation fg.deobf("dev.tr7zw:notenoughanimations-forge-1.11.1-mc1.20.1:1.10.0")
    implementation fg.deobf("dev.tr7zw:firstperson-forge-2.4.9-mc1.20.1:2.4.9")
    runtimeOnly fg.deobf("dev.tr7zw:TRender-1.0.10-1.20.1-forge-SNAPSHOT:1.0.5")
    runtimeOnly fg.deobf("dev.tr7zw:TRansition-1.0.11-1.20.1-forge-SNAPSHOT:1.0.3")

    // Vivecraft Mod.
    implementation fg.deobf("curse.maven:vivecraft-667903:7625923")

    implementation fg.deobf("curse.maven:thirst-was-taken-679270:6660408")
    implementation fg.deobf("curse.maven:trimmed-857036:4845938")

    // Botany Mod.
    implementation fg.deobf("curse.maven:bookshelf-228525:7612389")
    implementation fg.deobf("curse.maven:botany-pots-353928:7612402")

    implementation fg.deobf("curse.maven:create-328085:7178761")

    implementation fg.deobf("curse.maven:appleskin-248787:4770828")
    //implementation files("libs/Changed-m1.18.2-v0.14")
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
// When "copyIdeResources" is enabled, this will also run before the game launches in IDE environments.
// See https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.ProcessResources.html
//tasks.named('processResources', ProcessResources).configure {
//    var replaceProperties = [
//            minecraft_version   : minecraft_version, minecraft_version_range: minecraft_version_range,
//            forge_version       : forge_version, forge_version_range: forge_version_range,
//            loader_version_range: loader_version_range,
//            mod_id              : mod_id,
//            mod_name            : mod_name,
//            mod_license         : mod_license,
//              mod_version         : mod_version,
//            mod_authors         : mod_authors, mod_description: mod_description,
//    ]
//
//    inputs.properties replaceProperties
//
//    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
//        expand replaceProperties + [project: project]
//    }
//}

tasks.named('processResources', ProcessResources).configure {
    // List here all the "variablesKeys" of the mods.toml and pack.mcmeta
    def replacements = [
            'mod_version': mod_version.toString(),
    ]

    inputs.properties(replacements)

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        filter { line ->
            replacements.each { key, value ->
                // look for ${variableKey} and change for the value
                line = line.replace("\${${key}}", value)
            }
            line
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// Example for how to get properties into the manifest for reading at runtime.
jar {
    manifest {
        attributes([
                "Specification-Title"     : "changed_addon",
                "Specification-Vendor"    : "Foxyas",
                "Specification-Version"   : "1", // We are version 1 of ourselves
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : "${version}",
                "Implementation-Vendor"   : "Foxyas",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

// Example configuration to allow publishing using the maven-publish plugin
// This is the preferred method to reobfuscate your jar file
jar.finalizedBy('reobfJar')
// However if you are in a multi-project build, dev time needs unobfed jar files, so you can delay the obfuscation until publishing by doing
// publish.dependsOn('reobfJar')

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo/${minecraftVersion}"
        }
    }
}