org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraftVersion = 1.20.1
forgeVersion = 47.4.10
jeiVersion = 15.20.0.112
reiVersion = 12.1.785
clothVersion = 11.0.99
archVersion = 9.0.7

## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id = changed_addon
# The human-readable display name for the mod.
mod_name = Changed Addon Plus
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license = MIT License
# The mod version. See https://semver.org/
mod_version = 2.8.2
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id = com.foxyas.changed_addon
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_authors = Foxyas (Main Dev) \n0senia0 (Helper Dev)
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description = this is a §bremastered§r version of my mod addon hope you like it! \nIf you want to help me by donating some money this is my patreon https://www.patreon.com/foxyas\nand this is my ko-fi https://ko-fi.com/foxyas and if you want to support any other dev here is they ko-fi\n0senia0 https://ko-fi.com/0senia0
